server:
  port: 8082
spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/brilliomicroservice
    username: root
    password: Vishnu@139
#  jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
