server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: login-service
        uri: http://localhost:8083/
        predicates:
        - Path=/login/**
      - id: registration-service
        uri: http://localhost:8082/
        predicates:
        - Path=/registration/**   



  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
